Repository ENSTA-U2IS-AI/torch-uncertainty, pull requests merged in 2025-03, with the labels that each got.

#135 :bug: Fix MNIST test dataloader for shifted data
  .gitignore
  experiments/classification/mnist/configs/bayesian_lenet.yaml
  experiments/classification/mnist/configs/lenet.yaml
  experiments/classification/mnist/configs/lenet_checkpoint_ensemble.yaml
  experiments/classification/mnist/configs/lenet_ema.yaml
  experiments/classification/mnist/configs/lenet_swa.yaml
  experiments/classification/mnist/configs/lenet_swag.yaml
  tests/datamodules/classification/test_mnist.py
  torch_uncertainty/datamodules/abstract.py
  torch_uncertainty/datamodules/classification/cifar10.py
  torch_uncertainty/datamodules/classification/cifar100.py
  torch_uncertainty/datamodules/classification/imagenet.py
  torch_uncertainty/datamodules/classification/mnist.py
  torch_uncertainty/datamodules/classification/tiny_imagenet.py
  torch_uncertainty/routines/classification.py
Labels: bug

#134 🐳 Add Dockerfile and documentation for using Docker image
  .gitignore
  Dockerfile
  README.md
  docker/DOCKER.md
  docker/entrypoint.sh
Labels: enhancement

#140 :hammer: Use `kornia`'s motion blur instead of `Wand`'s Gaussian motion blur
  pyproject.toml
  tests/transforms/test_corruption.py
  torch_uncertainty/transforms/corruption.py
Labels: dependencies

#143 :hammer: make batch size and other parameters configurable in scaler fit method
  torch_uncertainty/post_processing/abstract.py
  torch_uncertainty/post_processing/calibration/scaler.py
  torch_uncertainty/post_processing/laplace.py
  torch_uncertainty/post_processing/mc_batch_norm.py
Labels: bug, enhancement

#144 :hammer: Improve the corruption transforms
  .github/workflows/run-tests.yml
  README.md
  pyproject.toml
  tests/datamodules/segmentation/test_muad.py
  tests/transforms/test_corruption.py
  torch_uncertainty/datasets/corrupted.py
  torch_uncertainty/datasets/muad.py
  torch_uncertainty/transforms/corruption.py
Labels: bug, documentation, enhancement

#156 :sparkles: Add an evalaluation batch size argument
  tests/_dummies/datamodule.py
  tests/datamodules/test_abstract_datamodule.py
  torch_uncertainty/datamodules/abstract.py
  torch_uncertainty/datamodules/classification/cifar10.py
  torch_uncertainty/datamodules/classification/cifar100.py
  torch_uncertainty/datamodules/classification/imagenet.py
  torch_uncertainty/datamodules/classification/mnist.py
  torch_uncertainty/datamodules/classification/tiny_imagenet.py
  torch_uncertainty/datamodules/classification/uci/bank_marketing.py
  torch_uncertainty/datamodules/classification/uci/dota2_games.py
  torch_uncertainty/datamodules/classification/uci/htru2.py
  torch_uncertainty/datamodules/classification/uci/online_shoppers.py
  torch_uncertainty/datamodules/classification/uci/spam_base.py
  torch_uncertainty/datamodules/classification/uci/uci_classification.py
  torch_uncertainty/datamodules/depth/base.py
  torch_uncertainty/datamodules/depth/kitti.py
  torch_uncertainty/datamodules/depth/muad.py
  torch_uncertainty/datamodules/depth/nyu.py
  torch_uncertainty/datamodules/segmentation/camvid.py
  torch_uncertainty/datamodules/segmentation/cityscapes.py
  torch_uncertainty/datamodules/segmentation/muad.py
  torch_uncertainty/datamodules/uci_regression.py
Labels: enhancement

#153 :hammer: Rework OOD criteria
  docs/source/api.rst
  docs/source/quickstart.rst
  tests/_dummies/baseline.py
  tests/routines/test_classification.py
  torch_uncertainty/baselines/classification/deep_ensembles.py
  torch_uncertainty/baselines/classification/resnet.py
  torch_uncertainty/baselines/classification/vgg.py
  torch_uncertainty/baselines/classification/wideresnet.py
  torch_uncertainty/ood_criteria.py
  torch_uncertainty/routines/classification.py
Labels: enhancement
