Repository ENSTA-U2IS-AI/torch-uncertainty, pull requests merged in 2025-07, with the labels that each got.

#195 :fire: Remove PyPI token
  .github/workflows/pypi-publish.yml
Labels: CI/CD

#198 🔧 Check that torch-uncertainty can be loaded without optional dependencies
  .github/workflows/run-tests.yml
Labels: CI/CD, dependencies

#199 :sparkles: Add complexity metrics
  torch_uncertainty/routines/classification.py
  torch_uncertainty/routines/pixel_regression.py
  torch_uncertainty/routines/regression.py
  torch_uncertainty/routines/segmentation.py
  torch_uncertainty/utils/evaluation_loop.py
Labels: enhancement

#205 :lock: Restrict releases
  .github/workflows/pypi-publish.yml
Labels: CI/CD, github_actions

#209 Improve the minimal dep checks & protect `tslearn`
  .github/workflows/run-tests.yml
  torch_uncertainty/datasets/classification/ucr_uea.py
Labels: CI/CD

#210 :bug: Fix unprotected optional dependency
  .github/workflows/run-tests.yml
  docs/source/conf.py
  pyproject.toml
  torch_uncertainty/datasets/classification/ucr_uea.py
Labels: bug, CI/CD
